version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: 13245
      MYSQL_DATABASE: API
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
